package com.mrkongtk.rtspviewer.data.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Represents a single RTSP stream configuration stored in the Room database.
 *
 * This entity serves as the main data model for the application, defining
 * the connection details and display preferences for a video stream.
 *
 * @property id The unique identifier for the item (auto-generated by Room).
 * @property name The user-defined display name for the stream.
 * @property uri The RTSP connection URI (e.g., rtsp://192.168.1.1...).
 * @property tags A list of categorical tags associated with this stream.
 * @property order The position index for sorting the list in the UI.
 * @property forceTcp Boolean flag to force the connection to use TCP instead of UDP. Defaults to false.
 */
@Serializable
@Entity(tableName = "rtsp_item")
data class RTSPItem(
    @PrimaryKey(autoGenerate = true)
    val id: Long,
    val name: String,
    val uri: String,
    val tags: List<String>,
    val order: Int,
    @ColumnInfo(name = "force_tcp")
    val forceTcp: Boolean = false,
) {
    /**
     * Generates a unique string representation of all object properties.
     *
     * This is used internally to simplify the implementation of [equals] and [hashCode].
     * Format: "id;name;uri;tag1,tag2;order;forceTcp"
     */
    private val stringify: String
        get() {
            return listOf(
                id.toString(),
                name,
                uri,
                tags.joinToString(","),
                order.toString(),
                forceTcp.toString()
            ).joinToString(";")
        }

    /**
     * Custom equality check.
     *
     * Unlike the standard data class implementation, this relies specifically
     * on the [stringify] property to determine equality.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        if (other !is RTSPItem) {
            return false
        }

        return this.stringify == other.stringify
    }

    /**
     * Generates a hash code based on the [stringify] representation.
     */
    override fun hashCode(): Int {
        return stringify.hashCode()
    }
}

/**
 * A data subset class used specifically for partial updates.
 *
 * This class allows the Room DAO to update only the sorting order of an item
 * without modifying (or needing to read) the other fields like name or URI.
 *
 * @property id The ID of the [RTSPItem] to update.
 * @property order The new order index to apply.
 */
data class RTSPItemOrderUpdate(
    @ColumnInfo(name = "id")
    val id: Long,
    @ColumnInfo(name = "order")
    val order: Int,
)
