package com.mrkongtk.rtspviewer.shared.data.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverter
import androidx.room.TypeConverters
import com.mrkongtk.rtspviewer.shared.data.database.dao.RTSPItemDao
import com.mrkongtk.rtspviewer.shared.data.database.entity.RTSPItem
import com.mrkongtk.rtspviewer.shared.di.AppDatabaseConstructor
import kotlinx.serialization.json.Json

/**
 * The core Room Database definition for the RTSP Viewer application.
 *
 * This abstract class serves as the main access point to the persisted data.
 * It manages the local SQLite database creation and version management,
 * acting as a bridge between the underlying SQLite tables and the DAO interfaces.
 *
 * @property rtspItemDao Provides access to database operations for [RTSPItem].
 */
@Database(
    entities = [RTSPItem::class], // List of all tables (entities) in this database
    version = 1,                  // The schema version; increment this when modifying entity structure
    exportSchema = true           // Exports schema to JSON for version control (check build.gradle arguments)
)
@TypeConverters(ListStringConverters::class) // Registers the custom type converter globally for this database
@ConstructedBy(AppDatabaseConstructor::class) // Required for KMP
abstract class AppDatabase : RoomDatabase() {

    /**
     * Retrieves the Data Access Object (DAO) for the [RTSPItem] table.
     *
     * @return An implementation of [RTSPItemDao] generated by Room.
     */
    abstract fun rtspItemDao(): RTSPItemDao
}

/**
 * A Room TypeConverter that enables storing [List] types as JSON strings.
 *
 * SQLite does not natively support storing collections. This class serializes a `List<String>`
 * into a JSON-formatted [String] for storage and deserializes it back into a list upon retrieval.
 *
 * **Strategy:**
 * This implementation uses Kotlinx Serialization (JSON). This is safer than manual
 * comma-separation because it automatically handles escaping for special characters,
 * quotes, and nested commas that would otherwise corrupt the data.
 */
class ListStringConverters {

    /**
     * Converts a JSON string from the database back into a [List] of strings.
     *
     * @param value The JSON-formatted string stored in the database (e.g., '["item1","item2"]').
     * @return A list of strings. Returns an empty list if the input is blank.
     */
    @TypeConverter
    fun fromString(value: String): List<String> {
        if (value.isBlank()) {
            return emptyList()
        }
        return Json.decodeFromString(value)
    }

    /**
     * Serializes a [List] of strings into a single JSON string for database storage.
     *
     * Using JSON ensures that:
     * 1. Data integrity is maintained regardless of the characters inside the strings.
     * 2. The format is standard and easily extensible if the data type changes later.
     *
     * @param list The list of strings to be stored.
     * @return A JSON array string representation of the list.
     */
    @TypeConverter
    fun fromList(list: List<String>): String {
        return Json.encodeToString(list)
    }
}
