package com.mrkongtk.rtspviewer.data.database

import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.TypeConverter
import androidx.room.TypeConverters
import com.mrkongtk.rtspviewer.data.database.dao.RTSPItemDao
import com.mrkongtk.rtspviewer.data.database.entity.RTSPItem
import java.net.URLDecoder
import java.net.URLEncoder

/**
 * The core Room Database definition for the RTSP Viewer application.
 *
 * This abstract class serves as the main access point to the persisted data.
 * It manages the local SQLite database creation and version management,
 * acting as a bridge between the underlying SQLite tables and the DAO interfaces.
 *
 * @property rtspItemDao Provides access to database operations for [RTSPItem].
 */
@Database(
    entities = [RTSPItem::class], // List of all tables (entities) in this database
    version = 1,                  // The schema version; increment this when modifying entity structure
    exportSchema = true           // Exports schema to JSON for version control (check build.gradle arguments)
)
@TypeConverters(ListStringConverters::class) // Registers the custom type converter globally for this database
abstract class AppDatabase : RoomDatabase() {

    /**
     * Retrieves the Data Access Object (DAO) for the [RTSPItem] table.
     *
     * @return An implementation of [RTSPItemDao] generated by Room.
     */
    abstract fun rtspItemDao(): RTSPItemDao
}

/**
 * A TypeConverter class to handle the persistence of [List] types in Room.
 *
 * SQLite does not natively support storing Lists or Arrays. This converter flattens
 * a `List<String>` into a single formatted `String` for storage and reconstructs it upon retrieval.
 *
 * **Encoding Strategy:**
 * It uses [URLEncoder] and [URLDecoder] to handle special characters.
 * This is crucial because if a simple comma delimiter was used, and one of the
 * items in the list contained a comma, the data would be corrupted upon retrieval.
 */
class ListStringConverters {

    /**
     * Converts a serialized String from the database back into a List object.
     *
     * It splits the source string by commas and URL-decodes each segment to recover
     * the original special characters.
     *
     * @param value The comma-separated, URL-encoded string stored in the database.
     * @return A [List] of original strings, or an empty list if [value] is empty.
     */
    @TypeConverter
    fun fromString(value: String): List<String> {
        if (value.isBlank()) {
            return emptyList()
        }

        return value.split(",").map { encodedItem ->
            try {
                URLDecoder.decode(encodedItem, Charsets.UTF_8.name())
            } catch (e: Exception) {
                // Fallback in case of decoding errors, or return raw string
                encodedItem
            }
        }
    }

    /**
     * Converts a List of Strings into a single String for database storage.
     *
     * Each item in the list is URL-encoded before joining. This ensures that:
     * 1. Commas within the data do not break the delimiter logic.
     * 2. Special characters (newlines, emojis, etc.) are safely stored as text.
     *
     * @param list The list of strings to be stored.
     * @return A single comma-separated string where every item is UTF-8 encoded.
     */
    @TypeConverter
    fun fromList(list: List<String>): String {
        return list.joinToString(",") { item ->
            URLEncoder.encode(item, Charsets.UTF_8.name())
        }
    }
}
