package com.mrkongtk.rtspviewer.ui.compose

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material3.Icon
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithContentDescription
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.onNodeWithText
import androidx.compose.ui.test.performClick
import androidx.core.graphics.createBitmap
import com.mrkongtk.rtspviewer.data.database.entity.RTSPItem
import com.mrkongtk.rtspviewer.ui.theme.RTSPViewerTheme
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Rule
import org.junit.Test

class StreamItemTest {

    @get:Rule
    val composeTestRule = createComposeRule()

    private val mockItem = RTSPItem(
        id = 1,
        name = "Front Door Camera",
        uri = "rtsp://example.com/live",
        tags = listOf("Outdoor", "Security"),
        order = 0
    )

    /**
     * Test Case: Verify that the stream name and all associated tags are rendered.
     */
    @Test
    fun streamItem_displaysNameAndTags() {
        composeTestRule.setContent {
            RTSPViewerTheme {
                StreamItem(
                    data = mockItem,
                    preview = null,
                    icon = { Icon(Icons.Default.PlayArrow, contentDescription = "Play") },
                    onClick = {}
                )
            }
        }

        // 1. Verify Name is displayed
        composeTestRule.onNodeWithText("Front Door Camera").assertIsDisplayed()

        // 2. Verify Tags are displayed.
        // Note: useUnmergedTree = true is necessary because FlowRow/Row often merges
        // children into a single semantic node for accessibility.
        composeTestRule.onNodeWithTag("Tag Outdoor", useUnmergedTree = true).assertIsDisplayed()
        composeTestRule.onNodeWithTag("Tag Security", useUnmergedTree = true).assertIsDisplayed()
    }

    /**
     * Test Case: Verify that the thumbnail image appears when a bitmap is provided.
     * It checks the content description generated by the formatText extension.
     */
    @Test
    fun streamItem_showsThumbnail_whenProvided() {
        val bitmap = createBitmap(100, 100).apply {
            eraseColor(Color.Red.toArgb())
        }

        composeTestRule.setContent {
            RTSPViewerTheme {
                StreamItem(
                    data = mockItem,
                    preview = bitmap,
                    icon = {},
                    onClick = {}
                )
            }
        }

        // We use substring = true because the formatText extension might add quotes
        // or extra characters depending on your string resource definition.
        composeTestRule.onNodeWithContentDescription(
            label = mockItem.name,
            substring = true,
            useUnmergedTree = true
        ).assertIsDisplayed()
    }

    /**
     * Test Case: Verify that clicking the item triggers the callback with the correct data.
     */
    @Test
    fun streamItem_click_triggersCallback() {
        var clickedItem: RTSPItem? = null

        composeTestRule.setContent {
            RTSPViewerTheme {
                StreamItem(
                    data = mockItem,
                    preview = null,
                    icon = {},
                    onClick = { clickedItem = it }
                )
            }
        }

        // Perform click on the item text (which is part of the clickable Card)
        composeTestRule.onNodeWithText("Front Door Camera").performClick()

        assertNotNull("Callback was not triggered", clickedItem)
        assertEquals(mockItem.id, clickedItem?.id)
        assertEquals(mockItem.name, clickedItem?.name)
    }

    /**
     * Test Case: Verify that the tag container or individual tags are absent
     * when the data object contains an empty list of tags.
     */
    @Test
    fun streamItem_hidesTags_whenListIsEmpty() {
        val itemNoTags = mockItem.copy(tags = emptyList())

        composeTestRule.setContent {
            RTSPViewerTheme {
                StreamItem(
                    data = itemNoTags,
                    preview = null,
                    icon = {},
                    onClick = {}
                )
            }
        }

        // Ensure nodes with specific tag identifiers do not exist
        composeTestRule.onNodeWithTag("Tag Outdoor").assertDoesNotExist()
        composeTestRule.onNodeWithTag("Tag Security").assertDoesNotExist()
    }

    /**
     * Test Case: Ensure the preview aspect ratio doesn't crash the UI with extreme values.
     */
    @Test
    fun streamItem_handlesThinBitmaps() {
        // Create a very thin bitmap to test aspectRatio(width/height)
        val thinBitmap = createBitmap(10, 100)

        composeTestRule.setContent {
            RTSPViewerTheme {
                StreamItem(
                    data = mockItem,
                    preview = thinBitmap,
                    icon = {},
                    onClick = {}
                )
            }
        }

        composeTestRule.onNodeWithText("Front Door Camera").assertIsDisplayed()
    }
}
