package com.mrkongtk.rtspviewer.shared.di

import androidx.room.RoomDatabaseConstructor
import com.mrkongtk.rtspviewer.shared.data.database.AppDatabase
import com.mrkongtk.rtspviewer.shared.data.repository.RTSPItemRepository
import com.mrkongtk.rtspviewer.shared.data.repository.RTSPItemRepositoryImpl
import com.mrkongtk.rtspviewer.shared.viewmodel.AppBarViewModel
import com.mrkongtk.rtspviewer.shared.viewmodel.AppViewModel
import org.koin.core.KoinApplication
import org.koin.core.context.startKoin
import org.koin.core.module.Module
import org.koin.core.module.dsl.viewModel
import org.koin.dsl.KoinAppDeclaration
import org.koin.dsl.includes
import org.koin.dsl.module

/**
 * Shared Koin module for dependencies available across all platforms.
 */
val commonModule = module {
    viewModel { AppBarViewModel() }
    viewModel { AppViewModel(get(), get()) }
    single<RTSPItemRepository> { RTSPItemRepositoryImpl(get(), get()) }
}

/**
 * Platform-specific module to be implemented in androidMain and iosMain.
 */
expect val platformModule: Module

/**
 * Required by Room for Kotlin Multiplatform to instantiate the database.
 * The 'actual' implementation is generated by the Room compiler.
 */
@Suppress("KotlinNoActualForExpect", "EXPECT_ACTUAL_CLASSIFIERS_ARE_IN_BETA_WARNING")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Entry point for Koin initialization.
 * To be called from the Android Application class or iOS App Delegate.
 */
fun initKoin(config: KoinAppDeclaration? = null): KoinApplication {
    return startKoin {
        includes(config)
        modules(
            commonModule,
            platformModule
        )
    }
}
